### PR TITLE
Contact Us section 

### PR DESCRIPTION
**Pull request by dagmawib**
I added a 'Contact Us' section that includes fields for the user's full name, phone number, email address, and message. Additionally, I added a Google map of our university for those who want to contact us in person.

### CODE REVIEW

**Comment by kalebalebachew** [comment]
That is perfect dagi. can you consider making the form fields a bit smaller? and thanks.

**Comment by dagmawib** [comment]
Okay, I will work on it, Kaleb. Thank you!

**Comment by dagmawib** [comment]
Hey Kaleb, I was working on the comment you gave me. Do you want me to make it smaller both vertically and horizontally, or could you clarify what you mean?

**Comment by kalebalebachew** [comment]
I meant it's a bit wide for a contact form making it smaller horizontally would be good i think and please first pull the changes from our side since we made a major layout change

**Pull request merged**
